name: foldingdiff
channels:
  - defaults
  - anaconda
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python=3.8
  - pip
  - anaconda::numpy=1.22.3
  - conda-forge::pandas~=1.1.5
  - pytorch::pytorch=1.12
  - huggingface::transformers=4.11.3
  - conda-forge::pytorch-lightning=1.6.4
  - conda-forge::huggingface_hub
  - conda-forge::seaborn
  - conda-forge::mpl-scatter-density
  - conda-forge::astropy=5.1
  - conda-forge::gitpython
  - conda-forge::biotite=0.34
  - bioconda::tmalign
  - conda-forge::requests
